[package]
name = "duder/risky-bomb"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
ReactRipple = "littensy/react-ripple@3.0.1"
Signal = "sleitnick/signal@2.0.3"
Janitor = "howmanysmall/janitor@1.18.3"
DataService = "leifstout/dataservice@0.4.0"
ReactCharm = "littensy/react-charm@0.3.0"
Charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"
Networker = "leifstout/networker@0.3.0"
Ripple = "littensy/ripple@0.10.1"